services:
  mysql:
    image: mysql:8.0
    container_name: mysql-weather
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db:/docker-entrypoint-initdb.d
volumes:
  db_data:
